export const PUSH_TEMP_STACK = 'PUSH_TEMP_STACK';
export const COMPUTE_TEMP_RESULT = 'COMPUTE_TEMP_RESULT';
export const COMPUTE_RESULT = 'COMPUTE_RESULT';
export const CLEAR_TEMP_STACK = 'CLEAR_TEMP_STACK';